### ISSUE TITLE
Need a little help getting this working…

### ISSUE THREAD

**Issue by benjaminwelch** [chrisgurney/things2md#5]

**Comment by benjaminwelch** [comment]
I really appreciate the work you put into this and I'm hoping I can get it working in Obsidian. I posted in Discussions for the Shell Command plugin which has most of the context here: https://github.com/Taitava/obsidian-shellcommands/discussions/411#discussion-6687873

I think there is some issue with my version of Python not being seen the Shell Commands PATH. You mentioned that you explicitly point to your version of Python but I wasn't sure where you did that. Any insight would be greatly appreciated. Thanks for your help.

**Comment by chrisgurney** [comment]
@benjaminwelch Sorry for the delay, I wasn't near my computer yesterday.

All I meant by that was that I included the full path to my Python install in the command I've setup in the Shell Commands plugin. The full command for executing the script that works for me is, for example:

`/opt/homebrew/bin/python3 ~/Development/things2md/things2md.py --today`

Give that a go and let me know if you make any progress.

**Comment by benjaminwelch** [comment]
That solved the issue. No worries about the delay. The help is much appreciated!
